#' Combine the results of rollmatch into a tidy list for output
#' As it's an internal helper function to aid in testing, it is not exported for use outside of the package.
#'
#' @param scored_data The dataset given to runModel with the additional of the
#' score values generated by the propensity score model
#' @param data_full The original data provided with the additional of
#' control weights
#' @param matches Dataframe containing the matches from comparison_pool
#' @param tm The time period indicator.
#' @param entry The time period in which the participant enrolled in the
#' intervention (in the same units as the tm variable).
#' @param lookback The number of time periods to look back before the
#' time period of enrollment (1-10).
#' 
#' @examples
#' \dontrun{ 
#' formula <- as.formula(treat ~ qtr_pmt + yr_pmt + age + is_male + is_white +
#'                        is_disabled + is_esrd + months_dual + chron_num + lq_ed +
#'                        yr_ed2 + lq_ip + yr_ip2)
#' tm <- "quarter"; entry <- "entry_q"; lookback <- 1
#' load(url(paste0("https://github.com/RTIInternational/rollmatch/raw/master/",
#'                 "tests/testthat/output.rda")))
#' scored_data <- output$scored_data
#' load(url(paste0("https://github.com/RTIInternational/rollmatch/raw/master/",
#'                 "tests/testthat/out_list.rda")))
#' data_full <- out_list$data_full
#' matches <- out_list$matches
#' out <- make_output(scored_data, data_full, matches, tm, entry, lookback)
#' head(out)
#' }
#' 
#' @return \code{output} returns a list containing the following components:
#' \item{scores}{The propensity scores used in matching.}
#' \item{data}{The original dataset with matches, scores, and weights applied.}
#' \item{summary}{A basic summary table.}
#' \item{ids_not_matched}{A vector of unmatched treatment ids}
#' \item{total_not_matched}{The count of unmatched treatment ids}
#' @keywords internal
make_output <- function(scored_data, data_full, matches,
                        treat, tm, entry, lookback){

  out <- list()
  out$scores <- scored_data$score
  out$data <- data_full
  # Number of Rows for Output
  treat_set <- data_full[data_full[[treat]] == 1 &
                           (data_full[[tm]] == data_full[[entry]] - lookback), ]
  comp_set <- data_full[data_full[[treat]] == 0 &
                          (data_full[[tm]] %in% unique(treat_set[[tm]])), ]
  
  nn <- matrix(0, ncol = 2, nrow = 3)
  treat_assigned <- length(unique(matches$treat_id))
  control_assigned <- length(unique(matches$control_id))
  nn[1, ] <- c(nrow(comp_set), nrow(treat_set))
  nn[2, ] <- c(control_assigned, treat_assigned)
  nn[3, ] <- c( (nrow(comp_set) - control_assigned),
                (nrow(treat_set) - treat_assigned))
  dimnames(nn) <- list(c("All", "Matched", "Unmatched"),
                       c("Control", "Treated"))
  out$summary <- nn
  
  all_ids <- unique(scored_data$indiv_id[scored_data[[treat]] == 1])
  discarded <- all_ids[ !(all_ids %in% unique(matches$treat_id))]
  out$ids_not_matched <- discarded
  out$total_not_matched <- length(discarded)
  out$matched_data <- matches
  return(out)
}
